version: '2'
services:
  mongo:
    image: mongo
  event-service:
    build: .
    command: java -jar /app/event-service-latest.jar --spring.data.mongodb.host="mongo"
#    enviroment:
#      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - mongo
