spring:
  cloud:
    config:
      server:
        git:
          uri:file://${pwd}/../config-repo
server:
  port:8020

spring:
  profiles:docker
  cloud:
      config:
        server:
          git:
            uri:https://
